name: build and test image

on:
  pull_request:
    branches: [ master ]

jobs:

  build-container:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      -
        name: Checkout
        uses: actions/checkout@v2
        
      
      # cache documentation: https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
      -
        name: Build with remote cache
        uses: docker/build-push-action@v2
        id: docker_build_dev
        with:
          context: .
          platforms: ${{ matrix.platform }}
          file: ./mbed-os-env/Dockerfile
          load: true
          cache-from: type=registry,ref=mbedos/mbed-os-env:latest

      - 
        name: test the container
        id: test
        uses: addnab/docker-run-action@v2
        with:
          options: -v ${{ github.workspace }}:/work -w=/work
          shell: bash
          run: |
            set -e
            echo "::set-output name=STATUS::failed"
            uname -m
            ./mbed-os-env/test.sh 
